toxcore/crypto_core.c, toxcore/crypto_core.h
I decided to go with the simple commit in the end.  There are a bunch of other issues I started covering, but I think they deserve their own tickets.
=> fixes #1210

docs/Avatars.md
=> fixed a typo

configure.ac, toxcore/DHT.c, toxcore/Messenger.c, toxcore/assoc.c, toxcore/logger.c, toxcore/logger.h, toxcore/network.c, toxcore/tox.c
- Added new level ``TRACE``
- ``INFO`` is greater than ``DEBUG``
- Cleaned up the mess
=> Logger fix

other/bootstrap_daemon/README.md, other/bootstrap_daemon/tox-bootstrapd.service
Added systemd unit file, and instructions for setup.
=> systemd additions for tox-bootstrapd

toxcore/tox.c, toxcore/tox.h
@irungentoo @nurupo @JFreegman 
The first commit should be included regardless, but I submit the second for discussion. (View it separately from the first.)
=> Tweaks to the new API

auto_tests/encryptsave_test.c, toxcore/tox.h, toxencryptsave/toxencryptsave.c, toxencryptsave/toxencryptsave.h
I haven't tested the auto_test yet, because /testing/tox_sync fails to compile and make aborts.
=> Toxencryptsave update

toxcore/network.c
Consistent with the other code in this project using LOGGER_DEBUG instead of fprintf and ifdef's for debug.
=> Change fprintf debug into LOGGER_DEBUG for consistency

auto_tests/tox_test.c, auto_tests/toxav_basic_test.c, auto_tests/toxav_many_test.c, testing/irc_syncbot.c, testing/nTox.c, testing/tox_shell.c, testing/tox_sync.c, toxcore/tox.c, toxcore/tox.h
Please review each commit separately, and cherry pick the ones you think are improvements.
For commits you disagree with, please specifically state what about the commit needs fixing for you to accept it.
I believe every single commit is worth merging, though one or two have some debatable parts, so *please* be specific about what you don't like.
=> API tweaks, this time separated into a bunch of small commits

auto_tests/tox_test.c, auto_tests/toxav_basic_test.c, auto_tests/toxav_many_test.c, testing/nTox.c, testing/tox_shell.c, testing/tox_sync.c, toxcore/tox.c, toxcore/tox.h
=> Move get_connection_status to self pseudonamespace, to contrast friend_get_connection_status

toxcore/tox.h
=> Documentation Error

auto_tests/encryptsave_test.c, toxencryptsave/toxencryptsave.c, toxencryptsave/toxencryptsave.h
Modifying autotests after API changes sucks major ass
=> Fix toxencryptsave to be consistent with new_api

INSTALL.md
* add install instructions for Gentoo
* adjust build instructions for presence of libsodium in some distros
=> Update INSTALL.md a bit

toxcore/crypto_core.c
Moving 'return -1;' directly below the conditions improves readability
and also better represents the coding style of other functions in
crypt_core.c (and everywhere else).
=> Improve readability of handle_request() in crypto_core.c

toxcore/TCP_connection.c, toxcore/TCP_connection.h
Also changed a duplicate function name.
=> Clarifications for the TCP API

docs/updates/Crypto.md
bob -> Bob
Bobs -> Bob's
and fixed some sentence.
=> small typo change

README.md
=> Add dev IRC channel to README, modify some phrasing slightly. 

auto_tests/messenger_test.c
"This will error" is grammatically incorrect, so I changed it to "This will give and error". "This will return an error is also fine"
=> Added ommited words in comment

README.md
Link taken from d9f88fd89ea37119cbfc64551251e33b20e507b0
=> Fix broken doc link

toxav/Makefile.inc, toxav/bwcontroller.c, toxav/bwcontroller.h, toxav/rtp.c, toxav/rtp.h, toxav/toxav.c
This is my pull request regarding Issue #1464.
=> fix BWController misspelling

other/bootstrap_daemon/src/log.c
Added default return to non void functions level_syslog and level_stdout.
=> Fix #1520: Program returns random data in a function

other/bootstrap_daemon/docker/Dockerfile
=> Rebase of #1511

dist-build/android-build.sh
[[ is a Bash feature not available in sh.
=> Change [[ to [
