irungentoo/toxcore

toxav/toxav.c
When trying to prepare an already active call, return av_ErrorAlreadyInCallWithPeer not av_ErrorNoCall
=> toxav_prepare_transmission: More descriptive error

toxcore/logger.c
[Apparently ERROR was defined as some constant somewhere on Windows, which was failing Windows build on Jenkins](https://jenkins.libtoxcore.so/job/libtoxcore-win32-x86_64/333/console).
Tested with `x86_64-w64-mingw32` for successful compilation.
=> Fixed Windows build

toxcore/logger.c
If on Windows, compile logging to output with "\r\n" instead of "\n".
=> Properly fix logging on Windows

other/bootstrap_daemon/tox-bootstrapd.conf
Reverts Proplex'es change, which was made solely for Tox packaging purposes, which I didn't agree with. Packaging should be kept away from toxcore repo.
=> Replace hardcoded nodes with examples

docs/Avatars.md, testing/test_avatars.c
Update the avatar documentation fixing some typos and formatting, adding unlisted function tox_unset_avatar, and updating the names "client id" to "public key" according to commit b8d530c9e0bbce331f22cbff7f818e49673d5bd7. Also updates the example "test_avatars.c".
=> Update avatar documentation and examples

other/bootstrap_node_packets.c
Fixed [a warning](https://travis-ci.org/irungentoo/toxcore/jobs/49821892#L532), caused by `packet_handler_callback` signature change.
```
$make
...
CC       ../other/bootstrap_daemon/tox_bootstrapd-tox-bootstrapd.o
In file included from ../other/bootstrap_daemon/tox-bootstrapd.c:51:0:
../other/bootstrap_daemon/../bootstrap_node_packets.c: In function ‘bootstrap_set_callbacks’:
../other/bootstrap_daemon/../bootstrap_node_packets.c:63:63: warning: passing argument 3 of ‘networking_registerhandler’ from incompatible pointer type
networking_registerhandler(net, BOOTSTRAP_INFO_PACKET_ID, &handle_info_request, net);
^
In file included from ../other/bootstrap_daemon/../../toxcore/crypto_core.h:26:0,
from ../other/bootstrap_daemon/../../toxcore/DHT.h:27,
from …
```
=> Fixed incompatible pointer type warning

toxcore/Messenger.c, toxcore/Messenger.h, toxcore/network.c, toxcore/network.h, toxcore/tox.c, toxcore/tox.h
Related to issue #1266.
Because of the multitude of `new_networking` calls in test and bootstrapd related files, I kept a `new_networking` that calls `new_networking_ex`.
This hasn't been tested as I don't know of any way to test new_api yet.
=> Allow for specifying the port range to use in Tox_Options

.gitignore, Makefile.am, configure.ac, tox.spec.in
The spec file gets processed by configure, the version will be filled
in automatically.
To generate an rpm make sure to install rpm-build, then "configure" as you
would usually do, run "make dist", then process the generated tarball
with rpmbuild:
rpmbuild -tb tox-0.0.0.tar.gz
This will produce a tox and tox-devel package.
I did not handle the DHT daemon yet but I can add it if needed.
Tested on Fedora 22.
=> add spec file for rpm packaging

toxcore/tox.c
According to the documentation, tox_options_new is supposed to initialize Tox_Options with default values but that doesn't actually happen.
This patch fixes that.
=> Initialize Tox_Options with default values in tox_options_new

auto_tests/tox_test.c, testing/nTox.c, testing/tox_sync.c, toxcore/tox.c, toxcore/tox.h
A couple of minor reasons, combined warrant a PR imo:
a) fileChunkRequested is a better signal name than fileRequestChunkReceived, and I don't want to break consistency by reordering words for just this signal
b) "request chunk" is parsed by English speakers as a verb-object combination,
implying sending the request, not receiving, whereas "chunk requested" is
parsed (more correctly) as an adjective-noun combo (in particular, request is
a noun not a verb), and thus reads far more like "hey heads up we just got a request"
For instance some tests/testing code had some callbacks to *receive* chunk requests, and they were called "tox_file_request_chunk"... to receive a chunk, not request it. Now they're called "tox_file_chunk_request".
So yeah...
@irungentoo @iphydf
=> callback_file_request_chunk -> callback_file_chunk_request

toxcore/tox.c
According to description of tox_new in tox.h, if length is 0, data should be ignored.
Before this fix tox_new returned error 10.
=> If length is 0, data should be ignored.

README.md
This reverts commit e294faeb4d94d38ead63246127e7691bad0a4cd5 that @urras submitted without actually realizing it was totally incorrect and unnecessary.
The documentation on libtoxcore.so was updated to reflect the new API in the tutorial perfectly in hours and the doxygen part is totally automated so it was technically up to date within about a minute of the new API being merged.
=> The documentation was fixed to reflect the new API the day it was merged, revert e294fae

toxcore/tox.h
There is no information in tox_friend_delete description about the behavior of friend numbers when this function is used.  But there is quite complex information in tox_firend_add description that includes deletion behavior. Reference to tox_friend_add  and basic ideas are added.
=> Additional description for tox_friend_delete.

toxcore/tox.h
This is to make explicit the fact that any properties of filenumbers and friendnumbers may change at any time without notice, and should therefore be treated as an unknown random number.
=> Amend comments to reflect undefined filenumber and friendnumber behavior

toxcore/Messenger.c, toxcore/Messenger.h, toxcore/tox.c, toxcore/tox.h
The removal of this function broke both Toxic and ToxBot. The reason given for its removal by @irungentoo was that some systems in rare cases might not handle the timestamps properly due to timezone setting incompatibilities (correct me if I'm wrong).
My argument is that we should not deprive 99.9% of users of useful functionality to account for these very rare cases, which would still only display an incorrect time and not actually break anything. Moreover, client developers should be able to use their own discretion.
=> API function to get last seen timestamp of friend

configure.ac
clock_gettime is in OpenBSD's libc
=> do not check for librt on OpenBSD

README.md
The link in README.md for TODO was 404:ing because the file TODO was changed from TODO to TODO.md.
=> Fixed 404ing link to TODO in README.md

other/bootstrap_daemon/README.md, other/bootstrap_daemon/tox-bootstrapd.service
@arthurtiteica has pointed out (https://github.com/irungentoo/toxcore/pull/1332) that systemd has more suitable facilities for creating a temporary directory for a PID file rather than calling  ExecStartPre, which requires an absolute path to coreutils executables we used for creating a directory and changing its owner, paths of which are are not universal across distributions. Systemd can take care of it for us without need to provide absolute paths, which is what we use here.
Tested on Debian Jessie -- worked for me.
@stqism you might want to check that it doesn't break the daemon package.
=> Updated daemon's systemd file, fixed typos in README

toxcore/assoc.c
assoc->self_client_id is always true, therefore we can remove it from that first if.
The if thus asserts !assoc->self_hash, so we can elide the immediately following if (!assoc->self_hash).
=> Remove pointless nullity check on array address

other/apidsl/tox.in.h, toxcore/tox.h
Apparently it's not entirely clear that it's not needed in clients.
=> Improve documentation about tcp_port

INSTALL.md
--Updated calls to package manager which is now  dnf by default 
--Mention of using  /etc/ld.so.conf directly which works and  in most distros *SHOULD NOT* cause  global override issues
=> Update info for Fedora

INSTALL.md
Note that Fedora dependencies section still needs to be actually checked by
someone who runs Fedora and would know whether info is right or not.
=> INSTALL.md: some formatting improvements and fixes

toxav/codec.c
Currently, APPLICATION_AUDIO is used, and so audio is not robust to packet loss. Audio decoding appears to be already set up to deal with packet loss, but the encoder is not. These changes should drastically improve audio quality on lossy connections like WiFi.
Note: I am not able to test this code at the moment. I can do so after next week and update this request if necessary.
=> Opus codec settings

INSTALL.md
The libVPX repository has been moved, as specified here:
http://www.webmproject.org/code/
=> Fix libVPX git repository

toxcore/Messenger.c
This fixes the PACKET_ID_OFFLINE handling code incorrectly falling through to the PACKET_ID_NICKNAME handling code
This bug resulted in a friend B's name being wiped on friend A's client after B removes A
Fixes tux3/qTox#1967
Fixes #1426
=> Fix PACKET_ID_OFFLINE fallinthrough PACKET_ID_NICKNAME

INSTALL.md
updated the git urls from `git` to `https`. The old urls are no longer supported.
=> updated git repo urls

auto_tests/TCP_test.c, testing/DHT_test.c, toxcore/DHT.c, toxcore/Messenger.c, toxcore/TCP_client.c, toxcore/TCP_connection.c, toxcore/TCP_server.c, toxcore/crypto_core.c, toxcore/crypto_core.h, toxcore/friend_connection.c, toxcore/friend_requests.c, toxcore/group.c, toxcore/net_crypto.c, toxcore/network.c, toxcore/onion_announce.c, toxcore/onion_client.c, toxcore/ping.c, toxcore/tox.c, toxcore/util.c
fix: compare sensitive data with sodium_memcmp
fix: replace memset with sodium_memzero for sensitive data
fix: make increment_nonce & increment_nonce_number independent of user-controlled input
fix: make crypto_core more stable agains null ptr dereference
fix: update apt before installing anything
add: comments about hairy code
=> Code review

.travis.yml
tox.h and toxav.h must be generated by apidsl instead of being edited directly.
From the Travis-CI you can see that toxav.h was edited directly by @mannol and @krobelus, it doesn't match the toxav.h generated by apidsl. These non-matching differences must be ported back into apidsl [toxav.in.h](https://github.com/irungentoo/toxcore/blob/master/other/apidsl/toxav.in.h).
=> Added check of whether tox.h or toxav.h were edited directly

other/bootstrap_daemon/src/Makefile.inc, toxcore/Makefile.inc, toxencryptsave/Makefile.inc
Currently archive created by `make dist` is incomplete.
Test to be run inside a repository clone:
```bash
#!/bin/sh
set -e -x
DIST=tox-0.0.0.tar.gz
./autogen.sh
./configure --prefix=/usr --enable-daemon
make dist
UNPACK_DIR=$(mktemp -d)
trap "rm -rf '$UNPACK_DIR'" EXIT
tar xf $DIST -C"$UNPACK_DIR/"
pushd "$UNPACK_DIR/$(basename $DIST .tar.gz)"
./configure --prefix=/usr --enable-daemon
make
popd
echo "OK"
```
=> Add missing files so that archive for make dist is complete

auto_tests/network_test.c, toxcore/network.c, toxcore/network.h
As I was figuring the reason `network_test` failed on my Fedora box (TL;DR: [#496300](https://bugzilla.redhat.com/show_bug.cgi?id=496300), Fedora does not ship `::1 localhost` in `/etc/hosts`), I stumbled upon `addr_resolve` code, which was reusing the `rc` from `getaddrinfo` and assigning values 1, 2, and 3 for AF_INET result, AF_INET6 result, and a flag that exact match was found respectively. It took me a while to understand what's going on, so I decided to introduce the following replacements for magic numbers:
```
/* addr_resolve return values */
#define TOX_ADDR_RESOLVE_INET  1
#define TOX_ADDR_RESOLVE_INET6 2
```
`3` was removed, since the return value is only checked in the test, and the latter does not care about the `3` case. `3` will be returned when the address resolved to …
=> Remove addr_resolve magic numbers

other/bootstrap_daemon/README.md
Update the manual to provide a command necessary to open <1024 ports for users on SysVinit
=> Documentation: SysVInit workaround for <1024 ports

auto_tests/Makefile.inc
tried to `make distcheck`. ran into this.
=> add missing header to dist tarball
